### ISSUE TITLE
Connection was closed. 

### ISSUE THREAD

**Issue by Observer5** [hyperf/jet#21]
`"exception":"[object] (Hyperf\\Jet\\Exception\\ConnectionException(code: 0): Connection was closed. at /var/www/dy/releases/75/vendor/hyperf/jet/src/Transporter/StreamSocketTransporter.php:94)
[stacktrace]
#0 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Support/helpers.php(393): Hyperf\\Jet\\Transporter\\StreamSocketTransporter->Hyperf\\Jet\\Transporter\\{closure}()
#1 /var/www/dy/releases/75/vendor/hyperf/jet/src/Transporter/StreamSocketTransporter.php(107): retry()
#2 /var/www/dy/releases/75/vendor/hyperf/jet/src/Transporter/StreamSocketTransporter.php(67): Hyperf\\Jet\\Transporter\\StreamSocketTransporter->receive()
#3 /var/www/dy/releases/75/vendor/hyperf/jet/src/AbstractClient.php(71): Hyperf\\Jet\\Transporter\\StreamSocketTransporter->recv()
#4 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Hyperf\\Jet\\AbstractClient->__call()
#5 /var/www/dy/releases/75/app/Services/EasyLiaoService.php(35): Illuminate\\Support\\Facades\\Facade::__callStatic()
#6 /var/www/dy/releases/75/app/Services/EasyLiaoService.php(54): App\\Services\\EasyLiaoService->createNum()
#7 /var/www/dy/releases/75/app/Services/EasyLiaoService.php(440): App\\Services\\EasyLiaoService->constructParams()
#8 /var/www/dy/releases/75/app/Jobs/CreateEasyLiaoClueJob.php(39): App\\Services\\EasyLiaoService->createClue()
#9 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\CreateEasyLiaoClueJob->handle()
#10 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#11 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#12 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#13 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#14 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call()
#15 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#16 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then()
#18 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow()
#19 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#20 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then()
#22 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#23 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call()
#24 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(368): Illuminate\\Queue\\Jobs\\Job->fire()
#25 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\\Queue\\Worker->process()
#26 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\\Queue\\Worker->runJob()
#27 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
#28 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#29 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#30 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#31 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#32 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#33 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\\Container\\BoundMethod::call()
#34 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#35 /var/www/dy/releases/75/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute()
#36 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#37 /var/www/dy/releases/75/vendor/symfony/console/Application.php(1009): Illuminate\\Console\\Command->run()
#38 /var/www/dy/releases/75/vendor/symfony/console/Application.php(273): Symfony\\Component\\Console\\Application->doRunCommand()
#39 /var/www/dy/releases/75/vendor/symfony/console/Application.php(149): Symfony\\Component\\Console\\Application->doRun()
#40 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#41 /var/www/dy/releases/75/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run()
#42 /var/www/dy/releases/75/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#43 {main}
"}`

- jet版本0.40
- Laravel 6 
- 消费队列里的抛的异常

**Comment by Observer5** [comment]
![image](https://user-images.githubusercontent.com/45023046/113412293-73d68100-93ea-11eb-9f46-3abf217965a1.png)
